from pathlib import Path

p = Path('backend/ecc/domains/communication/commitments.py')
s = p.read_text()
s = s.replace('from datetime import UTC, date, datetime, timedelta\n', 'from base64 import urlsafe_b64decode, urlsafe_b64encode\nfrom datetime import UTC, date, datetime, timedelta\n')
s = s.replace('from hashlib import sha256\n', 'from hashlib import sha256\nfrom hmac import compare_digest, new\n')
s = s.replace('from json import dumps\n', 'from json import dumps, loads\n')
s = s.replace('from ecc.database import get_session\n', 'from ecc.config import get_settings\nfrom ecc.database import get_session\n')
insert = '''\n\ndef _encode_cursor(created_at: datetime, commitment_id: UUID) -> str:\n    payload = dumps(\n        {"created_at": created_at.isoformat(), "id": str(commitment_id)},\n        separators=(",", ":"),\n    ).encode()\n    signature = new(get_settings().session_secret.encode(), payload, "sha256").hexdigest().encode()\n    return urlsafe_b64encode(payload + b"." + signature).decode().rstrip("=")\n\n\ndef _decode_cursor(cursor: str) -> tuple[datetime, UUID]:\n    try:\n        padded = cursor + "=" * (-len(cursor) % 4)\n        raw = urlsafe_b64decode(padded.encode())\n        payload, signature = raw.rsplit(b".", 1)\n        expected = new(get_settings().session_secret.encode(), payload, "sha256").hexdigest()\n        if not compare_digest(signature.decode(), expected):\n            raise ValueError\n        decoded = loads(payload)\n        return datetime.fromisoformat(decoded["created_at"]), UUID(decoded["id"])\n    except (ValueError, KeyError, TypeError, UnicodeDecodeError) as exc:\n        raise HTTPException(status_code=400, detail="MALFORMED_CURSOR") from exc\n\n\ndef _validate_references(\n    session: Session,\n    auth: AuthContext,\n    counterparty_person_id: UUID | None,\n    evidence_id: UUID | None,\n) -> None:\n    if counterparty_person_id is not None:\n        found = session.execute(\n            text(\n                """\n                SELECT 1 FROM pkos_nodes\n                WHERE workspace_id = :workspace_id AND id = :id AND node_type = 'person'\n                """\n            ),\n            {"workspace_id": auth.workspace_id, "id": counterparty_person_id},\n        ).scalar_one_or_none()\n        if found is None:\n            raise HTTPException(status_code=404, detail="COUNTERPARTY_NOT_FOUND")\n    if evidence_id is not None:\n        found = session.execute(\n            text(\n                """\n                SELECT 1 FROM pkos_evidence\n                WHERE workspace_id = :workspace_id AND id = :id\n                """\n            ),\n            {"workspace_id": auth.workspace_id, "id": evidence_id},\n        ).scalar_one_or_none()\n        if found is None:\n            raise HTTPException(status_code=404, detail="EVIDENCE_NOT_FOUND")\n'''
s = s.replace('\ndef _check_version(row: dict[str, Any], expected_version: int) -> None:\n', insert + '\n\ndef _check_version(row: dict[str, Any], expected_version: int) -> None:\n')
s = s.replace('        cached = _load_cached(session, auth, idempotency_key, request_hash)\n        if cached is not None:\n            return cached\n        row = (', '        cached = _load_cached(session, auth, idempotency_key, request_hash)\n        if cached is not None:\n            return cached\n        _validate_references(\n            session, auth, payload.counterparty_person_id, payload.evidence_id\n        )\n        row = (', 1)
s = s.replace('    include_archived: bool = False,\n    limit: int = Query(default=20, ge=1, le=100),\n', '    include_archived: bool = False,\n    cursor: str | None = None,\n    limit: int = Query(default=20, ge=1, le=100),\n')
s = s.replace('        "limit": limit,\n', '        "limit": limit + 1,\n', 1)
s = s.replace('    if pinned is not None:\n        clauses.append("pinned = :pinned")\n        params["pinned"] = pinned\n', '    if pinned is not None:\n        clauses.append("pinned = :pinned")\n        params["pinned"] = pinned\n    if cursor:\n        cursor_created_at, cursor_id = _decode_cursor(cursor)\n        clauses.append("(created_at, id) < (:cursor_created_at, :cursor_id)")\n        params["cursor_created_at"] = cursor_created_at\n        params["cursor_id"] = cursor_id\n', 1)
s = s.replace('    return CommitmentListResponse(items=[_to_response(dict(row)) for row in rows])\n', '    has_more = len(rows) > limit\n    page = rows[:limit]\n    next_cursor = None\n    if has_more and page:\n        last = page[-1]\n        next_cursor = _encode_cursor(last["created_at"], last["id"])\n    return CommitmentListResponse(\n        items=[_to_response(dict(row)) for row in page],\n        next_cursor=next_cursor,\n    )\n')
s = s.replace('        fields = payload.model_fields_set - {"expected_version"}\n', '        fields = payload.model_fields_set - {"expected_version"}\n        if "counterparty_person_id" in fields:\n            _validate_references(session, auth, payload.counterparty_person_id, None)\n')
s = s.replace('            or (action == "restore" and current["archived_at"] is None)\n', '')
p.write_text(s)

m = Path('backend/migrations/versions/0003_phase1_commitments.py')
s = m.read_text()
s = s.replace('    op.create_table(\n        "commitments",', '    op.create_unique_constraint(\n        "uq_pkos_evidence_workspace_id_id",\n        "pkos_evidence",\n        ["workspace_id", "id"],\n    )\n\n    op.create_table(\n        "commitments",')
s = s.replace('        sa.ForeignKeyConstraint(\n            ["workspace_id", "created_by"],', '        sa.ForeignKeyConstraint(\n            ["workspace_id", "counterparty_person_id"],\n            ["pkos_nodes.workspace_id", "pkos_nodes.id"],\n            name="fk_commitments_workspace_counterparty",\n        ),\n        sa.ForeignKeyConstraint(\n            ["workspace_id", "evidence_id"],\n            ["pkos_evidence.workspace_id", "pkos_evidence.id"],\n            name="fk_commitments_workspace_evidence",\n        ),\n        sa.ForeignKeyConstraint(\n            ["workspace_id", "created_by"],')
s = s.replace('    op.drop_table("commitments")\n', '    op.drop_table("commitments")\n    op.drop_constraint(\n        "uq_pkos_evidence_workspace_id_id",\n        "pkos_evidence",\n        type_="unique",\n    )\n')
m.write_text(s)

pt = Path('tests/test_commitment_postgres.py')
s = pt.read_text()
s = s.replace('    evidence_id = uuid4()\n\n    create = client.post(', '    evidence_id = uuid4()\n    evidence_node_id = uuid4()\n    with engine.begin() as connection:\n        connection.execute(\n            text(\n                """\n                INSERT INTO pkos_nodes (\n                    id, workspace_id, node_type, canonical_name, attributes,\n                    created_at, updated_at\n                ) VALUES (\n                    :id, :workspace_id, \'evidence\', :name, \'{}\'::jsonb, :now, :now\n                )\n                """\n            ),\n            {\n                "id": evidence_node_id,\n                "workspace_id": workspace_id,\n                "name": "Commitment evidence",\n                "now": datetime.now(UTC),\n            },\n        )\n        connection.execute(\n            text(\n                """\n                INSERT INTO pkos_evidence (\n                    id, workspace_id, node_id, source_type, source_ref, sha256, captured_at\n                ) VALUES (\n                    :id, :workspace_id, :node_id, \'test\', :source_ref, :sha256, :captured_at\n                )\n                """\n            ),\n            {\n                "id": evidence_id,\n                "workspace_id": workspace_id,\n                "node_id": evidence_node_id,\n                "source_ref": str(evidence_id),\n                "sha256": "0" * 64,\n                "captured_at": datetime.now(UTC),\n            },\n        )\n\n    create = client.post(')
s = s.replace('                "commitments",\n                "sessions",', '                "commitments",\n                "pkos_evidence",\n                "pkos_edges",\n                "pkos_nodes",\n                "sessions",')
s += '''\n\ndef test_restore_requires_archived_state(\n    commitment_test_context: tuple[TestClient, UUID, UUID, str],\n) -> None:\n    client, _, _, token = commitment_test_context\n    created = client.post(\n        "/api/v1/commitments",\n        headers=_headers(token, "restore-create"),\n        json={"summary": "Never archived", "direction": "made_by_me"},\n    ).json()\n    response = client.post(\n        f"/api/v1/commitments/{created['id']}/restore",\n        headers=_headers(token, "restore-invalid"),\n        json={"expected_version": created["version"]},\n    )\n    assert response.status_code == 409\n    assert response.json()["error"]["code"] == "COMMITMENT_NOT_ARCHIVED"\n\n\ndef test_commitment_list_uses_signed_cursor_pagination(\n    commitment_test_context: tuple[TestClient, UUID, UUID, str],\n) -> None:\n    client, _, _, token = commitment_test_context\n    for index in range(3):\n        response = client.post(\n            "/api/v1/commitments",\n            headers=_headers(token, f"page-create-{index}"),\n            json={"summary": f"Commitment {index}", "direction": "made_by_me"},\n        )\n        assert response.status_code == 201\n    first = client.get("/api/v1/commitments?limit=2")\n    assert first.status_code == 200\n    assert len(first.json()["items"]) == 2\n    assert first.json()["next_cursor"] is not None\n    second = client.get(\n        "/api/v1/commitments",\n        params={"limit": 2, "cursor": first.json()["next_cursor"]},\n    )\n    assert second.status_code == 200\n    assert len(second.json()["items"]) >= 1\n    malformed = client.get("/api/v1/commitments?cursor=not-signed")\n    assert malformed.status_code == 400\n\n\ndef test_cross_workspace_references_are_not_disclosed(\n    commitment_test_context: tuple[TestClient, UUID, UUID, str],\n) -> None:\n    client, _, _, token = commitment_test_context\n    response = client.post(\n        "/api/v1/commitments",\n        headers=_headers(token, "cross-workspace-reference"),\n        json={\n            "summary": "Invalid evidence",\n            "direction": "made_by_me",\n            "status": "detected",\n            "evidence_id": str(uuid4()),\n        },\n    )\n    assert response.status_code == 404\n    assert response.json()["error"]["code"] == "EVIDENCE_NOT_FOUND"\n'''
pt.write_text(s)
